{
 "title": "Hungry Hippo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "feed",
    "label": "Publisher",
    "query": {
     "query": "label_values(hippo_ingest_tick_price,feed_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingestion Rate (Ticks / Second)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (feed_id) (rate(hippo_ingest_ticks_total{feed_id=~\"$feed\"}[1m]))",
     "legendFormat": "{{feed_id}}"
    }
   ]
  },
  {
   "title": "Bad Data Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(hippo_ingest_ticks_total{is_corrected=\"true\", feed_id=~\"$feed\"}[1m])) \n/ \nsum(rate(hippo_ingest_ticks_total{feed_id=~\"$feed\"}[1m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anomalies Blocked (Last 1h)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hippo_ingest_ticks_total{is_corrected=\"true\", feed_id=~\"$feed\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anomaly Magnitude (Price Delta)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "sum by (feed_id) (hippo_ingest_tick_delta_total{feed_id=~\"$feed\"})",
     "legendFormat": "{{feed_id}}"
    }
   ]
  },
  {
   "title": "Raw vs Clean Price",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "hippo_ingest_tick_price{type=\"raw\", feed_id=~\"$feed\"}",
     "legendFormat": "{{feed_id}}"
    },
    {
     "expr": "hippo_ingest_tick_price{type=\"clean\", feed_id=~\"$feed\"}",
     "legendFormat": "{{feed_id}}"
    }
   ]
  }
 ]
}